#!/usr/bin/env python3
"""Generate a minimal AgentVST plugin skeleton from a validated JSON spec."""

from __future__ import annotations

import argparse
import json
import re
import shutil
from datetime import datetime, timezone
from pathlib import Path

from schema_tools import canonical_schema_path, load_json, make_validator, repo_root, validate_spec_data


def sanitize_identifier(text: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", text)
    cleaned = re.sub(r"_+", "_", cleaned).strip("_")
    if not cleaned:
        cleaned = "AgentPlugin"
    if cleaned[0].isdigit():
        cleaned = f"_{cleaned}"
    return cleaned


def has_parameter(spec: dict, param_id: str) -> bool:
    for parameter in spec.get("parameters", []):
        if parameter.get("id") == param_id:
            return True
    return False


def render_cmake(
    target_name: str,
    vendor: str,
    version: str,
    category: str,
) -> str:
    return (
        f"# Generated by scripts/generate.py\n"
        f"agentvst_add_plugin(\n"
        f"    NAME     {target_name}\n"
        f"    SCHEMA   \"${{CMAKE_CURRENT_SOURCE_DIR}}/plugin.json\"\n"
        f"    VENDOR   \"{vendor}\"\n"
        f"    VERSION  \"{version}\"\n"
        f"    CATEGORY \"{category}\"\n"
        f"    SOURCES\n"
        f"        src/{target_name}DSP.cpp\n"
        f")\n"
    )


def render_dsp(target_name: str, include_bypass: bool, include_gain: bool) -> str:
    includes = "#include <AgentDSP.h>\n"
    if include_gain:
        includes += "#include <cmath>\n"

    bypass_block = ""
    if include_bypass:
        bypass_block = (
            "        if (ctx.getParameter(\"bypass\") >= 0.5f)\n"
            "            return input;\n\n"
        )

    if include_gain:
        process_tail = (
            "        const float gainDb = ctx.getParameter(\"gain_db\");\n"
            "        const float linear = std::pow(10.0f, gainDb / 20.0f);\n"
            "        return input * linear;\n"
        )
    else:
        process_tail = (
            "        // TODO: Replace pass-through with audible DSP logic.\n"
            "        // AgentVST logs a potential no-op warning if output remains\n"
            "        // effectively identical to input for many consecutive blocks.\n"
            "        return input;\n"
        )

    return (
        "/**\n"
        " * Generated DSP scaffold.\n"
        " *\n"
        " * Keep processSample real-time safe:\n"
        " * - no allocations\n"
        " * - no locks\n"
        " * - no I/O\n"
        " */\n"
        f"{includes}\n"
        f"class {target_name}Processor : public AgentVST::IAgentDSP {{\n"
        "public:\n"
        "    void prepare(double /*sampleRate*/, int /*maxBlockSize*/) override {}\n\n"
        "    float processSample(int /*channel*/, float input,\n"
        "                        const AgentVST::DSPContext& ctx) override {\n"
        f"{bypass_block}"
        f"{process_tail}"
        "    }\n\n"
        "    void reset() override {}\n"
        "};\n\n"
        f"AGENTVST_REGISTER_DSP({target_name}Processor)\n"
    )


def render_readme(spec_name: str, target_name: str, spec_path: Path, generated_at: str) -> str:
    return (
        f"# {spec_name} (Generated Scaffold)\n\n"
        f"This directory was generated from `{spec_path}` at {generated_at}.\n\n"
        "## Files\n\n"
        f"- `plugin.json` - validated schema input copied into this directory\n"
        f"- `CMakeLists.txt` - `agentvst_add_plugin` entry for `{target_name}`\n"
        f"- `src/{target_name}DSP.cpp` - starter `processSample` implementation\n\n"
        "## Next Steps\n\n"
        "1. Add this folder with `add_subdirectory(...)` in your root CMake project.\n"
        "2. Refine DSP logic in the generated source file.\n"
        "3. Validate schema changes with `python scripts/validate_schema.py <path-to-plugin.json>`.\n"
        "4. During testing, check logs for `Potential no-op DSP detected` warnings.\n\n"
        "## Troubleshooting\n\n"
        "- If audio sounds unchanged, verify your DSP does not return input unchanged under active settings.\n"
        "- If build succeeds but DAW still runs old behavior, ensure plugin deploy copy was not blocked by a host lock.\n"
        "- Close the DAW (or unload plugin), rebuild, and confirm the deployed `.vst3` timestamp changed.\n"
    )


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", required=True, help="Path to plugin spec JSON file.")
    parser.add_argument(
        "--out",
        default="generated",
        help="Output directory for generated plugin folder (default: generated).",
    )
    parser.add_argument(
        "--schema",
        default=None,
        help="Optional schema path override (default: schema/plugin.schema.json).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing generated plugin folder.",
    )
    args = parser.parse_args()

    root = repo_root()
    spec_path = Path(args.spec)
    if not spec_path.is_absolute():
        spec_path = (root / spec_path).resolve()

    if not spec_path.is_file():
        raise FileNotFoundError(f"Spec file not found: {spec_path}")

    schema_path = Path(args.schema).resolve() if args.schema else canonical_schema_path(root)
    if not schema_path.is_file():
        raise FileNotFoundError(f"Schema file not found: {schema_path}")

    spec_data = load_json(spec_path)
    validator = make_validator(schema_path)
    errors = validate_spec_data(validator, spec_data, str(spec_path))
    if errors:
        joined = "\n".join(f"- {error}" for error in errors)
        raise ValueError(f"Spec failed validation:\n{joined}")

    plugin_meta = spec_data.get("plugin", {})
    spec_name = plugin_meta.get("name", spec_path.stem)
    target_name = sanitize_identifier(spec_name)

    output_root = Path(args.out)
    if not output_root.is_absolute():
        output_root = (root / output_root).resolve()

    plugin_dir = output_root / target_name
    if plugin_dir.exists():
        if not args.force:
            raise FileExistsError(f"Output folder already exists: {plugin_dir}. Use --force to overwrite.")
        shutil.rmtree(plugin_dir)

    include_bypass = has_parameter(spec_data, "bypass")
    include_gain = has_parameter(spec_data, "gain_db")

    write_text(plugin_dir / "plugin.json", json.dumps(spec_data, indent=2) + "\n")
    write_text(
        plugin_dir / "CMakeLists.txt",
        render_cmake(
            target_name=target_name,
            vendor=plugin_meta.get("vendor", "AgentVST"),
            version=plugin_meta.get("version", "1.0.0"),
            category=plugin_meta.get("category", "Fx"),
        ),
    )
    write_text(
        plugin_dir / "src" / f"{target_name}DSP.cpp",
        render_dsp(target_name, include_bypass=include_bypass, include_gain=include_gain),
    )

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    write_text(
        plugin_dir / "README.md",
        render_readme(spec_name=spec_name, target_name=target_name, spec_path=spec_path, generated_at=generated_at),
    )

    print(f"[OK] Generated plugin scaffold at: {plugin_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
