/**
 * InitCommand.cpp
 * agentvst init <PluginName> [--vendor <VendorName>] [--version <x.y.z>]
 *
 * Scaffolds a new plugin project:
 *   <PluginName>/
 *   ├── plugin.json
 *   ├── src/<PluginName>DSP.cpp
 *   └── CMakeLists.txt
 */
#include "InitCommand.h"
#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <filesystem>
#include <algorithm>

namespace AgentVST::CLI {

namespace fs = std::filesystem;

static void writeFile(const fs::path& path, const std::string& content) {
    fs::create_directories(path.parent_path());
    std::ofstream f(path);
    if (!f.is_open())
        throw std::runtime_error("Cannot create file: " + path.string());
    f << content;
    std::cout << "  Created: " << path.string() << "\n";
}

int runInit(const std::vector<std::string>& args) {
    if (args.empty()) {
        std::cerr << "Usage: agentvst init <PluginName> [--vendor <Name>] [--version <x.y.z>]\n";
        return 1;
    }

    std::string pluginName = args[0];
    std::string vendor     = "AgentVST";
    std::string version    = "1.0.0";

    for (std::size_t i = 1; i < args.size(); ++i) {
        if (args[i] == "--vendor"  && i + 1 < args.size()) { vendor  = args[++i]; }
        if (args[i] == "--version" && i + 1 < args.size()) { version = args[++i]; }
    }

    const fs::path projectDir = fs::current_path() / pluginName;

    if (fs::exists(projectDir)) {
        std::cerr << "[ERROR] Directory already exists: " << projectDir.string() << "\n";
        return 1;
    }

    std::cout << "Creating AgentVST plugin project: " << pluginName << "\n";

    // ── plugin.json ──────────────────────────────────────────────────────────
    const std::string schemaJson =
        "{\n"
        "  \"plugin\": {\n"
        "    \"name\":     \"" + pluginName + "\",\n"
        "    \"version\":  \"" + version + "\",\n"
        "    \"vendor\":   \"" + vendor + "\",\n"
        "    \"category\": \"Fx\"\n"
        "  },\n"
        "  \"parameters\": [\n"
        "    {\n"
        "      \"id\":      \"gain_db\",\n"
        "      \"name\":    \"Gain\",\n"
        "      \"type\":    \"float\",\n"
        "      \"min\":     -60.0,\n"
        "      \"max\":     12.0,\n"
        "      \"default\": 0.0,\n"
        "      \"unit\":    \"dB\"\n"
        "    },\n"
        "    {\n"
        "      \"id\":      \"bypass\",\n"
        "      \"name\":    \"Bypass\",\n"
        "      \"type\":    \"boolean\",\n"
        "      \"default\": false\n"
        "    }\n"
        "  ],\n"
        "  \"groups\": [\n"
        "    { \"id\": \"main\", \"name\": \"Main\", \"parameters\": [\"gain_db\", \"bypass\"] }\n"
        "  ]\n"
        "}\n";
    writeFile(projectDir / "plugin.json", schemaJson);

    // ── CMakeLists.txt ────────────────────────────────────────────────────────
    const std::string cmake =
        "# " + pluginName + "/CMakeLists.txt\n"
        "# Generated by: agentvst init " + pluginName + "\n\n"
        "agentvst_add_plugin(\n"
        "    NAME     " + pluginName + "\n"
        "    SCHEMA   \"${CMAKE_CURRENT_SOURCE_DIR}/plugin.json\"\n"
        "    VENDOR   \"" + vendor + "\"\n"
        "    VERSION  \"" + version + "\"\n"
        "    CATEGORY \"Fx\"\n"
        "    SOURCES\n"
        "        src/" + pluginName + "DSP.cpp\n"
        ")\n";
    writeFile(projectDir / "CMakeLists.txt", cmake);

    // ── DSP stub ─────────────────────────────────────────────────────────────
    const std::string dspName = pluginName + "Processor";
    const std::string dsp =
        "/**\n"
        " * " + pluginName + "DSP.cpp\n"
        " * Generated by: agentvst init " + pluginName + "\n"
        " *\n"
        " * REAL-TIME CONSTRAINTS — prohibited in processSample():\n"
        " *   new / delete / malloc / push_back    (heap allocation)\n"
        " *   std::cout / printf / DBG              (I/O / system calls)\n"
        " *   std::mutex / unique_lock              (blocking locks)\n"
        " */\n"
        "#include <AgentDSP.h>\n"
        "#include <cmath>\n\n"
        "class " + dspName + " : public AgentVST::IAgentDSP {\n"
        "public:\n"
        "    void prepare(double sampleRate, int /*maxBlockSize*/) override {\n"
        "        sampleRate_  = sampleRate;\n"
        "        smoothCoeff_ = std::exp(-1.0 / (sampleRate_ * 0.020)); // 20ms ramp\n"
        "        smoothedGain_ = 1.0f;\n"
        "    }\n\n"
        "    float processSample(int /*channel*/, float input,\n"
        "                        const AgentVST::DSPContext& ctx) override {\n"
        "        if (ctx.getParameter(\"bypass\") >= 0.5f)\n"
        "            return input;\n\n"
        "        const float gainDb = ctx.getParameter(\"gain_db\");\n"
        "        const float target = (gainDb <= -59.5f)\n"
        "                                ? 0.0f\n"
        "                                : std::pow(10.0f, gainDb / 20.0f);\n\n"
        "        smoothedGain_ = static_cast<float>(smoothCoeff_) * smoothedGain_\n"
        "                      + (1.0f - static_cast<float>(smoothCoeff_)) * target;\n\n"
        "        return input * smoothedGain_;\n"
        "    }\n\n"
        "    void reset() override { smoothedGain_ = 1.0f; }\n\n"
        "private:\n"
        "    double sampleRate_    = 44100.0;\n"
        "    double smoothCoeff_   = 0.999;\n"
        "    float  smoothedGain_  = 1.0f;\n"
        "};\n\n"
        "AGENTVST_REGISTER_DSP(" + dspName + ")\n";
    writeFile(projectDir / "src" / (pluginName + "DSP.cpp"), dsp);

    std::cout << "\n[OK] Plugin project scaffolded at: " << projectDir.string() << "\n\n"
              << "NEXT STEPS:\n"
              << "  1. Edit " << pluginName << "/plugin.json to define your parameters\n"
              << "  2. Edit " << pluginName << "/src/" << pluginName
              << "DSP.cpp to implement processSample()\n"
              << "  3. Validate: agentvst validate " << pluginName << "/plugin.json\n"
              << "  4. Check DSP: agentvst validate-dsp "
              << pluginName << "/src/" << pluginName << "DSP.cpp\n"
              << "  5. Add to your CMakeLists.txt: add_subdirectory(" << pluginName << ")\n";
    return 0;
}

} // namespace AgentVST::CLI
